---
- hosts: webservers 
  become: True
  tasks:
    - name: Install packages
      apt:
        name: "apache2"
        state: "present"
    - name: Start Apache server
      service:
        name: apache2
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: k8s.yml
        dest: /home/ubuntu/
    - name: Execute a command using the shell module
      shell: kubectl --kubeconfig=/home/dialog/.kube/config apply -f k8s.yml
...
